concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "f587a9af300a-dev"
  url = "https://gitlab.com/"
  token = "R5AQLLu4u8nGLG4tYnXr"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
